server:
    port: 8080
    servelet:
      context-path:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://worbiqqclswlhv:e497ee2e7304cf7ef04d5206f6a661448aa4e5ad2c8d7928214d1761ab403e62@ec2-3-226-134-153.compute-1.amazonaws.com:5432/d4egsf5jsq9sq7
    username: worbiqqclswlhv
    password: e497ee2e7304cf7ef04d5206f6a661448aa4e5ad2c8d7928214d1761ab403e62
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgresSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Criado para o bootcamp DIO - Santander -trainee Rafael Bondioli.